//country action types
export const country = {
    COUNTRY_LOAD_START: 'COUNTRY_LOAD_START',
    COUNTRY_LOAD_SUCCESS: 'COUNTRY_LOAD_SUCCESS',
    COUNTRY_LOAD_ERROR: 'COUNTRY_LOAD_ERROR'
};
//country action types end

//banks action types
export const banks = {
    BANK_LOAD_START: 'BANK_LOAD_START',
    BANK_LOAD_SUCCESS: 'BANK_LOAD_SUCCESS',
    BANK_LOAD_ERROR: 'BANK_LOAD_ERROR'
};
//banks action types end
//biller category action types
export const billerCategory = {
    BILLERCATEGORY_LOAD_START: 'BILLERCATEGORY_LOAD_START',
    BILLERCATEGORY_LOAD_SUCCESS: 'BILLERCATEGORY_LOAD_SUCCESS',
    BILLERCATEGORY_LOAD_ERROR: 'BILLERCATEGORY_LOAD_ERROR'
};
//biller category action types end

//banks action types
export const billerType = {
    BILLERTYPE_LOAD_START: 'BILLERTYPE_LOAD_START',
    BILLERTYPE_LOAD_SUCCESS: 'BILLERTYPE_LOAD_SUCCESS',
    BILLERTYPE_LOAD_ERROR: 'BILLERTYPE_LOAD_ERROR'
};
//banks action types end
//banks action types
export const billerPlan = {
    BILLERPLAN_LOAD_START: 'BILLERPLAN_LOAD_START',
    BILLERPLAN_LOAD_SUCCESS: 'BILLERPLAN_LOAD_SUCCESS',
    BILLERPLAN_LOAD_ERROR: 'BILLERPLAN_LOAD_ERROR'
};
//banks action types end

//language action types

export const languages = {
    LANGUAGE_LOAD_START: 'LANGUAGE_LOAD_START',
    LANGUAGE_LOAD_SUCCESS: 'LANGUAGE_LOAD_SUCCESS',
    LANGUAGE_LOAD_ERROR: 'LANGUAGE_LOAD_ERROR'
};

//language action type ends

//Airtime action types

export const airtime = {
    AIRTIME_LOAD_START: 'AIRTIME_LOAD_START',
    AIRTIME_LOAD_SUCCESS: 'AIRTIME_LOAD_SUCCESS',
    AIRTIME_LOAD_ERROR: 'AIRTIME_LOAD_ERROR'
};

//Airtime action type ends

//AirtimeNetwork action types

export const airtimeNetwork = {
    AIRTIMENETWORK_LOAD_START: 'AIRTIMENETWORK_LOAD_START',
    AIRTIMENETWORK_LOAD_SUCCESS: 'AIRTIMENETWORK_LOAD_SUCCESS',
    AIRTIMENETWORK_LOAD_ERROR: 'AIRTIMENETWORK_LOAD_ERROR'
};

//AirtimeNetwork action type ends

//setTransactionPin action types

export const setTransactionPin = {
    SETTRANSACTIONPIN_LOAD_START: 'SETTRANSACTIONPIN_LOAD_START',
    SETTRANSACTIONPIN_LOAD_SUCCESS: 'SETTRANSACTIONPIN_LOAD_SUCCESS',
    SETTRANSACTIONPIN_LOAD_ERROR: 'SETTRANSACTIONPIN_LOAD_ERROR'
};

//setTransactionPin action type ends

//Bills action types

export const bills = {
    BILLS_LOAD_START: 'BILLS_LOAD_START',
    BILLS_LOAD_SUCCESS: 'BILLS_LOAD_SUCCESS',
    BILLS_LOAD_ERROR: 'BILLS_LOAD_ERROR'
};

//Bills action type ends

//Internal action types

export const internalBank = {
    INTERNALBANK_LOAD_START: 'INTERNALBANK_LOAD_START',
    INTERNALBANK_LOAD_SUCCESS: 'INTERNALBANK_LOAD_SUCCESS',
    INTERNALBANK_LOAD_ERROR: 'INTERNALBANK_LOAD_ERROR'
};

//Internal action type ends
//Inter action types

export const interBank = {
    INTERBANK_LOAD_START: 'INTERBANK_LOAD_START',
    INTERBANK_LOAD_SUCCESS: 'INTERBANK_LOAD_SUCCESS',
    INTERBANK_LOAD_ERROR: 'INTERBANK_LOAD_ERROR'
};

//Inter action type ends

//Inter action types

export const interBankEnquiry = {
    INTERBANKENQUIRY_LOAD_START: 'INTERBANKENQUIRY_LOAD_START',
    INTERBANKENQUIRY_LOAD_SUCCESS: 'INTERBANKENQUIRY_LOAD_SUCCESS',
    INTERBANKENQUIRY_LOAD_ERROR: 'INTERBANKENQUIRY_LOAD_ERROR'
};

//Inter action type ends

//balanceEnquiry action types

export const balanceEnquiry = {
    BALANCEENQUIRY_LOAD_START: 'BALANCEENQUIRY_LOAD_START',
    BALANCEENQUIRY_LOAD_SUCCESS: 'BALANCEENQUIRY_LOAD_SUCCESS',
    BALANCEENQUIRY_LOAD_ERROR: 'BALANCEENQUIRY_LOAD_ERROR'
};

//balanceENquiry action type ends

//transactionHistory action types

export const transactionHistory = {
    TRANSACTIONHISTORY_LOAD_START: 'TRANSACTIONHISTORY_LOAD_START',
    TRANSACTIONHISTORY_LOAD_SUCCESS: 'TRANSACTIONHISTORY_LOAD_SUCCESS',
    TRANSACTIONHISTORY_LOAD_ERROR: 'TRANSACTIONHISTORY_LOAD_ERROR'
};

//transactionHistory action type ends

//transactionElevate action types

export const transactionElevate = {
    TRANSACTIONELEVATE_LOAD_START: 'TRANSACTIONELEVATE_LOAD_START',
    TRANSACTIONELEVATE_LOAD_SUCCESS: 'TRANSACTIONELEVATE_LOAD_SUCCESS',
    TRANSACTIONELEVATE_LOAD_ERROR: 'TRANSACTIONELEVATE_LOAD_ERROR'
};

//transactionElevate action type ends

//getBeneficiaries action types

export const getBeneficiaries = {
    GETBENEFICIARIES_LOAD_START: 'GETBENEFICIARIES_LOAD_START',
    GETBENEFICIARIES_LOAD_SUCCESS: 'GETBENEFICIARIES_LOAD_SUCCESS',
    GETBENEFICIARIES_LOAD_ERROR: 'GETBENEFICIARIES_LOAD_ERROR'
};

//getBeneficiaries action type ends

//deleteBeneficiaries action types

export const deleteBeneficiaries = {
    DELETEBENEFICIARIES_LOAD_START: 'DELETEBENEFICIARIES_LOAD_START',
    DELETEBENEFICIARIES_LOAD_SUCCESS: 'DELETEBENEFICIARIES_LOAD_SUCCESS',
    DELETEBENEFICIARIES_LOAD_ERROR: 'DELETEBENEFICIARIES_LOAD_ERROR'
};

//deleteBeneficiaries action type ends

//viewBvn action types

export const viewBvn = {
    VIEWBVN_LOAD_START: 'VIEWBVN_LOAD_START',
    VIEWBVN_LOAD_SUCCESS: 'VIEWBVN_LOAD_SUCCESS',
    VIEWBVN_LOAD_ERROR: 'VIEWBVN_LOAD_ERROR'
};

//viewBvn action type ends

//resetPassword action types

export const resetPassword = {
    RESETPASSWORD_LOAD_START: 'RESETPASSWORD_LOAD_START',
    RESETPASSWORD_LOAD_SUCCESS: 'RESETPASSWORD_LOAD_SUCCESS',
    RESETPASSWORD_LOAD_ERROR: 'RESETPASSWORD_LOAD_ERROR'
};

//resetPassword action type ends

//bankStatement action types

export const bankStatement = {
    BANKSTATEMENT_LOAD_START: 'BANKSTATEMENT_LOAD_START',
    BANKSTATEMENT_LOAD_SUCCESS: 'BANKSTATEMENT_LOAD_SUCCESS',
    BANKSTATEMENT_LOAD_ERROR: 'BANKSTATEMENT_LOAD_ERROR'
};

//bankStatement action type ends

//ussdgen action types

export const ussdGen = {
    USSDGEN_LOAD_START: 'USSDGEN_LOAD_START',
    USSDGEN_LOAD_SUCCESS: 'USSDGEN_LOAD_SUCCESS',
    USSDGEN_LOAD_ERROR: 'USSDGEN_LOAD_ERROR'
};

//ussdgen action type ends

//ussdStatus action types

export const ussdStatus = {
    USSDSTATUS_LOAD_START: 'USSDSTATUS_LOAD_START',
    USSDSTATUS_LOAD_SUCCESS: 'USSDSTATUS_LOAD_SUCCESS',
    USSDSTATUS_LOAD_ERROR: 'USSDSTATUS_LOAD_ERROR'
};

//ussdStatus action type ends

//postBeneficiaries action types

export const postBeneficiaries = {
    POSTBENEFICIARIES_LOAD_START: 'POSTBENEFICIARIES_LOAD_START',
    POSTBENEFICIARIES_LOAD_SUCCESS: 'POSTBENEFICIARIES_LOAD_SUCCESS',
    POSTBENEFICIARIES_LOAD_ERROR: 'POSTBENEFICIARIES_LOAD_ERROR'
};

//postBeneficiaries action type ends

//transactionHistory action types

export const bulkTransfer = {
    BULKTRANSFER_LOAD_START: 'BULKTRANSFER_LOAD_START',
    BULKTRANSFER_LOAD_SUCCESS: 'BULKTRANSFER_LOAD_SUCCESS',
    BULKTRANSFER_LOAD_ERROR: 'BULKTRANSFER_LOAD_ERROR'
};

//transactionHistory action type ends

//verifyBank action types

export const verifyBank = {
    VERIFYBANK_LOAD_START: 'VERIFYBANK_LOAD_START',
    VERIFYBANK_LOAD_SUCCESS: 'VERIFYBANK_LOAD_SUCCESS',
    VERIFYBANK_LOAD_ERROR: 'VERIFYBANK_LOAD_ERROR'
};

//verifyBank action type ends

//VerifyCurrency action types

export const verifyCurrency = {
    VERIFYCURRENCY_LOAD_START: 'VERIFYCURRENCY_LOAD_START',
    VERIFYCURRENCY_LOAD_SUCCESS: 'VERIFYCURRENCY_LOAD_SUCCESS',
    VERIFYCURRENCY_LOAD_ERROR: 'VERIFYCURRENCY_LOAD_ERROR'
};

//VerifyCurrency action type ends

//transactionHistory action types

export const internationalTransfer = {
    INTERNATIONALTRANSFER_LOAD_START: 'INTERNATIONALTRANSFER_LOAD_START',
    INTERNATIONALTRANSFER_LOAD_SUCCESS: 'INTERNATIONALTRANSFER_LOAD_SUCCESS',
    INTERNATIONALTRANSFER_LOAD_ERROR: 'INTERNATIONALTRANSFER_LOAD_ERROR'
};

//transactionHistory action type ends

//omnilite action types

export const omnilite = {
    OMNILITE_LOAD_START: 'OMNILITE_LOAD_START',
    OMNILITE_LOAD_SUCCESS: 'OMNILITE_LOAD_SUCCESS',
    OMNILITE_LOAD_ERROR: 'OMNILITE_LOAD_ERROR'
};

//omnilite action type ends

//ecobankOnline action types

export const ecobankOnline = {
    ECOBANKONLINE_LOAD_START: 'ECOBANKONLINE_LOAD_START',
    ECOBANKONLINE_LOAD_SUCCESS: 'ECOBANKONLINE_LOAD_SUCCESS',
    ECOBANKONLINE_LOAD_ERROR: 'ECOBANKONLINE_LOAD_ERROR'
};

//ecobankOnline action type ends

//accountNumber action types

export const accountNumber = {
    ACCOUNTNUMBER_LOAD_START: 'ACCOUNTNUMBER_LOAD_START',
    ACCOUNTNUMBER_LOAD_SUCCESS: 'ACCOUNTNUMBER_LOAD_SUCCESS',
    ACCOUNTNUMBER_LOAD_ERROR: 'ACCOUNTNUMBER_LOAD_ERROR'
};

//accountNumber action type ends

//accountNumber action types

export const existingUserProfile = {
    EXISTINGUSERPROFILE_LOAD_START: 'EXISTINGUSERPROFILE_LOAD_START',
    EXISTINGUSERPROFILE_LOAD_SUCCESS: 'EXISTINGUSERPROFILE_LOAD_SUCCESS',
    EXISTINGUSERPROFILE_LOAD_ERROR: 'EXISTINGUSERPROFILE_LOAD_ERROR'
};

//accountNumber action type ends

//accountNumber action types

export const createAccount = {
    CREATEACCOUNT_LOAD_START: 'CREATEACCOUNT_LOAD_START',
    CREATEACCOUNT_LOAD_SUCCESS: 'CREATEACCOUNT_LOAD_SUCCESS',
    CREATEACCOUNT_LOAD_ERROR: 'CREATEACCOUNT_LOAD_ERROR'
};

//accountNumber action type ends

//accountNumber action types

export const accountStatus = {
    ACCOUNTSTATUS_LOAD_START: 'ACCOUNTSTATUS_LOAD_START',
    ACCOUNTSTATUS_LOAD_SUCCESS: 'ACCOUNTSTATUS_LOAD_SUCCESS',
    ACCOUNTSTATUS_LOAD_ERROR: 'ACCOUNTSTATUS_LOAD_ERROR'
};

//accountNumber action type ends

//businessCategory action types

export const businessCategories = {
    BUSINESSCATEGORIES_LOAD_START: 'BUSINESSCATEGORIES_LOAD_START',
    BUSINESSCATEGORIES_LOAD_SUCCESS: 'BUSINESSCATEGORIES_LOAD_SUCCESS',
    BUSINESSCATEGORIES_LOAD_ERROR: 'BUSINESSCATEGORIES_LOAD_ERROR'
};

//businessCategory action type ends

//states action types

export const states = {
    STATES_LOAD_START: 'STATES_LOAD_START',
    STATES_LOAD_SUCCESS: 'STATES_LOAD_SUCCESS',
    STATES_LOAD_ERROR: 'STATES_LOAD_ERROR'
};

//states action type ends

//cardLogin action types

export const cardLogin = {
    CARDLOGIN_LOAD_START: 'CARDLOGIN_LOAD_START',
    CARDLOGIN_LOAD_SUCCESS: 'CARDLOGIN_LOAD_SUCCESS',
    CARDLOGIN_LOAD_ERROR: 'CARDLOGIN_LOAD_ERROR'
};

//cardLogin action type ends

//auth action types
export const login = {
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_START: 'REGISTER_START',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROE',
    SET_MESSAGE: 'SET_MESSAGE',
    CLEAR_MESSAGE: 'CLEAR_MESSAGE',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    LOGIN_START: 'LOGIN_START'
};
//end auth action types
//profile setup

export const setupProfile = {
    PROFILESETUP_LOAD_START: 'PROFILE_SETUPLOAD_START',
    PROFILESETUP_LOAD_SUCCESS: 'PROFILESETUP_LOAD_SUCCESS',
    PROFILESETUP_LOAD_ERROR: 'PROFILESETUP_LOAD_ERROR',
    BVN_NIN_LOAD_ERROR: 'BVN_NIN_LOAD_ERROR',
    BVN_NIN_LOAD_ERRORI: 'BVN_NIN_LOAD_ERRORI',
    BVN_NIN_LOAD_ERRORII: 'BVN_NIN_LOAD_ERRORII',
    BVN_NIN_LOAD_ERRORIII: 'BVN_NIN_LOAD_ERRORIII',
    BVN_NIN_LOAD_SUCCESS: 'BVN_NIN_LOAD_SUCCESS',
    BVN_NIN_LOAD_PENDING: 'BVN_NIN_LOAD_PENDING'
};
//profile setup end

//Bus profile setup

export const setupBusProfile = {
    BUS_PROFILESETUP_LOAD_START: 'BUS_PROFILE_SETUPLOAD_START',
    BUS_PROFILESETUP_LOAD_SUCCESS: 'BUS_PROFILESETUP_LOAD_SUCCESS',
    BUS_PROFILESETUP_LOAD_ERROR: 'BUS_PROFILESETUP_LOAD_ERROR',
    BUS_BVN_NIN_LOAD_ERROR: 'BUS_BVN_NIN_LOAD_ERROR',
    BUS_BVN_NIN_LOAD_ERRORI: 'BUS_BVN_NIN_LOAD_ERRORI',
    BUS_BVN_NIN_LOAD_ERRORII: 'BUS_BVN_NIN_LOAD_ERRORII',
    BUS_BVN_NIN_LOAD_ERRORIII: 'BUS_BVN_NIN_LOAD_ERRORIII',
    BUS_BVN_NIN_LOAD_SUCCESS: 'BUS_BVN_NIN_LOAD_SUCCESS',
    BUS_BVN_NIN_LOAD_PENDING: 'BUS_BVN_NIN_LOAD_PENDING'
};
//Bus profile setup end

//complete profile action type start

export const compProfile = {
    PROFILE_LOAD_START: 'PROFILE_LOAD_START',
    PROFILE_LOAD_SUCCESS: 'PROFILE_LOAD_SUCCESS',
    PROFILE_LOAD_ERROR: 'PROFILE_LOAD_ERROR'
};

//complete profile action type end

//complete profile action type start

export const userProfile = {
    USERPROFILE_LOAD_START: 'USERPROFILE_LOAD_START',
    USERPROFILE_LOAD_SUCCESS: 'USERPROFILE_LOAD_SUCCESS',
    USERPROFILE_LOAD_ERROR: 'USERPROFILE_LOAD_ERROR'
};

//complete profile action type end

//complete profile action type start

export const accountPrimary = {
    ACCOUNTPRIMARY_LOAD_START: 'ACCOUNTPRIMARY_LOAD_START',
    ACCOUNTPRIMARY_LOAD_SUCCESS: 'ACCOUNTPRIMARY_LOAD_SUCCESS',
    ACCOUNTPRIMARY_LOAD_ERROR: 'ACCOUNTPRIMARY_LOAD_ERROR'
};

//complete profile action type end

//ot action type start

export const otp = {
    OTP_LOAD_START: 'OTP_LOAD_START',
    OTP_LOAD_SUCCESS: 'OTP_LOAD_SUCCESS',
    OTP_LOAD_ERROR: 'OTP_LOAD_ERROR'
};
//otp action type end

//complete profile start
export const completeProfile = {
    COMP_PROFILE_LOAD_START: 'COMP_PROFILE_LOAD_START',
    COMP_PROFILE_LOAD_SUCCESS: 'COMP_PROFILE_LOAD_SUCCESS',
    COMP_PROFILE_LOAD_ERROR: 'COMP_PROFILE_LOAD_ERROR'
};
//complete profile end

//create new user account
export const newUserCreateAccount = {
    CREATE_NEW_ACCOUNT_LOAD_START: 'CREATE_NEW_ACCOUNT_LOAD_START',
    CREATE_NEW_ACCOUNT_LOAD_SUCCESS: 'CREATE_NEW_ACCOUNT_LOAD_SUCCESS',
    CREATE_NEW_ACCOUNT_LOAD_ERROR: 'CREATE_NEW_ACCOUNT_LOAD_ERROR'
};
//create new user end

//get new user account start

export const getNewUserAccount = {
    GET_NEW_ACCOUNT_LOAD_START: 'GET_NEW_ACCOUNT_LOAD_START',
    GET_NEW_ACCOUNT_LOAD_SUCCESS: 'GET_NEW_ACCOUNT_LOAD_SUCCESS',
    GET_NEW_ACCOUNT_LOAD_ERROR: 'GET_NEW_ACCOUNT_LOAD_ERROR'
};

//get new user account end

//create new user Corp account
export const newUserCreateCorpAccount = {
    CREATE_NEW_CORP_ACCOUNT_LOAD_START: 'CREATE_NEW_CORP_ACCOUNT_LOAD_START',
    CREATE_NEW_CORP_ACCOUNT_LOAD_SUCCESS:
        'CREATE_NEW_CORP_ACCOUNT_LOAD_SUCCESS',
    CREATE_NEW_CORP_ACCOUNT_LOAD_ERROR: 'CREATE_NEW_CORP_ACCOUNT_LOAD_ERROR'
};
//create new user Corp end

//get user bank account
export const getUserBankAccounts = {
    GET_USER_Bank_ACCOUNTS_ACCOUNT_LOAD_START:
        'GET_USER_Bank_ACCOUNTS_ACCOUNT_LOAD_START',
    GET_USER_Bank_ACCOUNTS_ACCOUNT_LOAD_SUCCESS:
        'GET_USER_Bank_ACCOUNTS_ACCOUNT_LOAD_SUCCESS',
    GET_USER_Bank_ACCOUNTS_ACCOUNT_LOAD_ERROR:
        'GET_USER_Bank_ACCOUNTS_ACCOUNT_LOAD_ERROR'
};
//get user bank account

//BBOARD RESOLUTION TYPE STARTE
export const uploadBoardResType = {
    GET_BOARD_RESOLUTION_START: 'GET_BOARD_RESOLUTION_START',
    GET_BOARD_RESOLUTION_SUCCESS: 'GET_BOARD_RESOLUTION_SUCCESS',
    GET_BOARD_RESOLUTION_ERROR: 'GET_BOARD_RESOLUTION_ERROR'
};
//BOARD RESOLUTION TYPE ENDS

//CAC CERTIFICATE TYPE STARTE
export const uploadCacCertType = {
    GET_CAC_CERIFICATE_START: 'GET_CAC_CERIFICATE_START',
    GET_CAC_CERIFICATE_SUCCESS: 'GET_CAC_CERIFICATE_SUCCESS',
    GET_CAC_CERIFICATEERROR: 'GET_CAC_CERIFICATE_ERROR'
};
//CAC CERTIFICATE TYPE ENDS

//IDENTIFICATION DOC TYPE STARTE
export const uploadIdDocType = {
    GET_ID_DOCUMENTATION_START: 'GET_ID_DOCUMENTATION_START',
    GET_ID_DOCUMENTATION_SUCCESS: 'GET_ID_DOCUMENTATION_SUCCESS',
    GET_ID_DOCUMENTATION_ERROR: 'GET_ID_DOCUMENTATION_ERROR'
};
//IDENTIFICATION DOCTYPE ENDS

//MEMART DOC TYPE STARTE
export const uploadMemartType = {
    GET_MEMART_START: 'GET_MEMART_START',
    GET_MEMART_SUCCESS: 'GET_MEMART_SUCCESS',
    GET_MEMART_ERROR: 'GET_MEMART_ERROR'
};
//MEMART DOCTYPE ENDS

//REFFERENCE FORM TYPE STARTE
export const uploadRefferenceFormType = {
    GET_REFFERENCE_FORM_START: 'GET_REFFERENCE_FORM_START',
    GET_REFFERENCE_FORM_SUCCESS: 'GET_REFFERENCE_FORM_SUCCESS',
    GET_REFFERENCE_FORM_ERROR: 'GET_REFFERENCE_FORM_ERROR'
};
//REFFERENCE FORM ENDS

//SCMUL FORM TYPE STARTE
export const uploadScmulType = {
    GET_SCMUL_START: 'GET_SCMUL_START',
    GET_SCMUL_SUCCESS: 'GET_SCMUL_SUCCESS',
    GET_SCMUL_ERROR: 'GET_SCMUL_ERROR'
};
//SCMULFORM ENDS

//UTILITY DOCUMENT FORM TYPE STARTE
export const uploadUtilityDocumentype = {
    GET_UTILITY_DOCUMENT_START: 'GET_UTILITY_DOCUMENT_START',
    GET_UTILITY_DOCUMENT_SUCCESS: 'GET_UTILITY_DOCUMENTL_SUCCESS',
    GET_UTILITY_DOCUMENT_ERROR: 'GET_UTILITY_DOCUMENT_ERROR'
};
//UTILITY DOCUMENTFORM ENDS

//SHAEE REFFERNCE FORM TYPE STARTE
export const shareRefFormtype = {
    GET_SHARE_REFFERENCE_START: 'GET_SHARE_REFFERENCE_START',
    GET_SHARE_REFFERENCE_SUCCESS: 'GET_SHARE_REFFERENCE_SUCCESS',
    GET_SHARE_REFFERENCE_ERROR: 'GET_SHARE_REFFERENCE_ERROR'
};
//SHAEE REFFERNCE FORM ENDS

//Forgot Password TYPE STARTE
export const forgotPasswordtype = {
    GET_FORGOT_PASSWORD_START: 'GET_FORGOT_PASSWORD_START',
    GET_FORGOT_PASSWORD_SUCCESS: 'GET_FORGOT_PASSWORD_SUCCESS',
    GET_FORGOT_PASSWORD_ERROR: 'GET_FORGOT_PASSWORD_ERROR'
};
// Forgot Password ENDS

//Reset otp TYPE STARTE
export const resetOtpType = {
    RESET_OTP_START: 'RESET_OTP_START',
    RESET_OTP_SUCCESS: 'RESET_OTP_SUCCESS',
    RESET_OTP_PASSWORD_ERROR: 'RESET_OTP_ERROR'
};
// FReset otp End
