//country action types
export const country = {
    COUNTRY_LOAD_START: 'COUNTRY_LOAD_START',
    COUNTRY_LOAD_SUCCESS: 'COUNTRY_LOAD_SUCCESS',
    COUNTRY_LOAD_ERROR: 'COUNTRY_LOAD_ERROR'
};
//country action types end

//banks action types
export const banks = {
    BANK_LOAD_START: 'BANK_LOAD_START',
    BANK_LOAD_SUCCESS: 'BANK_LOAD_SUCCESS',
    BANK_LOAD_ERROR: 'BANK_LOAD_ERROR'
};
//banks action types end
//biller category action types
export const billerCategory = {
    BILLERCATEGORY_LOAD_START: 'BILLERCATEGORY_LOAD_START',
    BILLERCATEGORY_LOAD_SUCCESS: 'BILLERCATEGORY_LOAD_SUCCESS',
    BILLERCATEGORY_LOAD_ERROR: 'BILLERCATEGORY_LOAD_ERROR'
};
//biller category action types end

//banks action types
export const billerType = {
    BILLERTYPE_LOAD_START: 'BILLERTYPE_LOAD_START',
    BILLERTYPE_LOAD_SUCCESS: 'BILLERTYPE_LOAD_SUCCESS',
    BILLERTYPE_LOAD_ERROR: 'BILLERTYPE_LOAD_ERROR'
};
//banks action types end
//banks action types
export const billerPlan = {
    BILLERPLAN_LOAD_START: 'BILLERPLAN_LOAD_START',
    BILLERPLAN_LOAD_SUCCESS: 'BILLERPLAN_LOAD_SUCCESS',
    BILLERPLAN_LOAD_ERROR: 'BILLERPLAN_LOAD_ERROR'
};
//banks action types end

//language action types

export const languages = {
    LANGUAGE_LOAD_START: 'LANGUAGE_LOAD_START',
    LANGUAGE_LOAD_SUCCESS: 'LANGUAGE_LOAD_SUCCESS',
    LANGUAGE_LOAD_ERROR: 'LANGUAGE_LOAD_ERROR'
};

//language action type ends

//Airtime action types

export const airtime = {
    AIRTIME_LOAD_START: 'AIRTIME_LOAD_START',
    AIRTIME_LOAD_SUCCESS: 'AIRTIME_LOAD_SUCCESS',
    AIRTIME_LOAD_ERROR: 'AIRTIME_LOAD_ERROR'
};

//Airtime action type ends

//Bills action types

export const bills = {
    BILLS_LOAD_START: 'BILLS_LOAD_START',
    BILLS_LOAD_SUCCESS: 'BILLS_LOAD_SUCCESS',
    BILLS_LOAD_ERROR: 'BILLS_LOAD_ERROR'
};

//Bills action type ends

//Internal action types

export const internalBank = {
    INTERNALBANK_LOAD_START: 'INTERNALBANK_LOAD_START',
    INTERNALBANK_LOAD_SUCCESS: 'INTERNALBANK_LOAD_SUCCESS',
    INTERNALBANK_LOAD_ERROR: 'INTERNALBANK_LOAD_ERROR'
};

//Internal action type ends
//Inter action types

export const interBank = {
    INTERBANK_LOAD_START: 'INTERBANK_LOAD_START',
    INTERBANK_LOAD_SUCCESS: 'INTERBANK_LOAD_SUCCESS',
    INTERBANK_LOAD_ERROR: 'INTERBANK_LOAD_ERROR'
};

//Inter action type ends

//Inter action types

export const interBankEnquiry = {
    INTERBANKENQUIRY_LOAD_START: 'INTERBANKENQUIRY_LOAD_START',
    INTERBANKENQUIRY_LOAD_SUCCESS: 'INTERBANKENQUIRY_LOAD_SUCCESS',
    INTERBANKENQUIRY_LOAD_ERROR: 'INTERBANKENQUIRY_LOAD_ERROR'
};

//Inter action type ends

//balanceEnquiry action types

export const balanceEnquiry = {
    BALANCEENQUIRY_LOAD_START: 'BALANCEENQUIRY_LOAD_START',
    BALANCEENQUIRY_LOAD_SUCCESS: 'BALANCEENQUIRY_LOAD_SUCCESS',
    BALANCEENQUIRY_LOAD_ERROR: 'BALANCEENQUIRY_LOAD_ERROR'
};

//balanceENquiry action type ends

//transactionHistory action types

export const transactionHistory = {
    TRANSACTIONHISTORY_LOAD_START: 'TRANSACTIONHISTORY_LOAD_START',
    TRANSACTIONHISTORY_LOAD_SUCCESS: 'TRANSACTIONHISTORY_LOAD_SUCCESS',
    TRANSACTIONHISTORY_LOAD_ERROR: 'TRANSACTIONHISTORY_LOAD_ERROR'
};

//transactionHistory action type ends

//transactionElevate action types

export const transactionElevate = {
    TRANSACTIONELEVATE_LOAD_START: 'TRANSACTIONELEVATE_LOAD_START',
    TRANSACTIONELEVATE_LOAD_SUCCESS: 'TRANSACTIONELEVATE_LOAD_SUCCESS',
    TRANSACTIONELEVATE_LOAD_ERROR: 'TRANSACTIONELEVATE_LOAD_ERROR'
};

//transactionElevate action type ends

//getBeneficiaries action types

export const getBeneficiaries = {
    GETBENEFICIARIES_LOAD_START: 'GETBENEFICIARIES_LOAD_START',
    GETBENEFICIARIES_LOAD_SUCCESS: 'GETBENEFICIARIES_LOAD_SUCCESS',
    GETBENEFICIARIES_LOAD_ERROR: 'GETBENEFICIARIES_LOAD_ERROR'
};

//getBeneficiaries action type ends

//postBeneficiaries action types

export const postBeneficiaries = {
    POSTBENEFICIARIES_LOAD_START: 'POSTBENEFICIARIES_LOAD_START',
    POSTBENEFICIARIES_LOAD_SUCCESS: 'POSTBENEFICIARIES_LOAD_SUCCESS',
    POSTBENEFICIARIES_LOAD_ERROR: 'POSTBENEFICIARIES_LOAD_ERROR'
};

//postBeneficiaries action type ends

//transactionHistory action types

export const bulkTransfer = {
    BULKTRANSFER_LOAD_START: 'BULKTRANSFER_LOAD_START',
    BULKTRANSFER_LOAD_SUCCESS: 'BULKTRANSFER_LOAD_SUCCESS',
    BULKTRANSFER_LOAD_ERROR: 'BULKTRANSFER_LOAD_ERROR'
};

//transactionHistory action type ends

//verifyBank action types

export const verifyBank = {
    VERIFYBANK_LOAD_START: 'VERIFYBANK_LOAD_START',
    VERIFYBANK_LOAD_SUCCESS: 'VERIFYBANK_LOAD_SUCCESS',
    VERIFYBANK_LOAD_ERROR: 'VERIFYBANK_LOAD_ERROR'
};

//verifyBank action type ends

//VerifyCurrency action types

export const verifyCurrency = {
    VERIFYCURRENCY_LOAD_START: 'VERIFYCURRENCY_LOAD_START',
    VERIFYCURRENCY_LOAD_SUCCESS: 'VERIFYCURRENCY_LOAD_SUCCESS',
    VERIFYCURRENCY_LOAD_ERROR: 'VERIFYCURRENCY_LOAD_ERROR'
};

//VerifyCurrency action type ends

//transactionHistory action types

export const internationalTransfer = {
    INTERNATIONALTRANSFER_LOAD_START: 'INTERNATIONALTRANSFER_LOAD_START',
    INTERNATIONALTRANSFER_LOAD_SUCCESS: 'INTERNATIONALTRANSFER_LOAD_SUCCESS',
    INTERNATIONALTRANSFER_LOAD_ERROR: 'INTERNATIONALTRANSFER_LOAD_ERROR'
};

//transactionHistory action type ends

//omnilite action types

export const omnilite = {
    OMNILITE_LOAD_START: 'OMNILITE_LOAD_START',
    OMNILITE_LOAD_SUCCESS: 'OMNILITE_LOAD_SUCCESS',
    OMNILITE_LOAD_ERROR: 'OMNILITE_LOAD_ERROR'
};

//omnilite action type ends

//ecobankOnline action types

export const ecobankOnline = {
    ECOBANKONLINE_LOAD_START: 'ECOBANKONLINE_LOAD_START',
    ECOBANKONLINE_LOAD_SUCCESS: 'ECOBANKONLINE_LOAD_SUCCESS',
    ECOBANKONLINE_LOAD_ERROR: 'ECOBANKONLINE_LOAD_ERROR'
};

//ecobankOnline action type ends

//accountNumber action types

export const accountNumber = {
    ACCOUNTNUMBER_LOAD_START: 'ACCOUNTNUMBER_LOAD_START',
    ACCOUNTNUMBER_LOAD_SUCCESS: 'ACCOUNTNUMBER_LOAD_SUCCESS',
    ACCOUNTNUMBER_LOAD_ERROR: 'ACCOUNTNUMBER_LOAD_ERROR'
};

//accountNumber action type ends

//accountNumber action types

export const existingUserProfile = {
    EXISTINGUSERPROFILE_LOAD_START: 'EXISTINGUSERPROFILE_LOAD_START',
    EXISTINGUSERPROFILE_LOAD_SUCCESS: 'EXISTINGUSERPROFILE_LOAD_SUCCESS',
    EXISTINGUSERPROFILE_LOAD_ERROR: 'EXISTINGUSERPROFILE_LOAD_ERROR'
};

//accountNumber action type ends

//accountNumber action types

export const createAccount = {
    CREATEACCOUNT_LOAD_START: 'CREATEACCOUNT_LOAD_START',
    CREATEACCOUNT_LOAD_SUCCESS: 'CREATEACCOUNT_LOAD_SUCCESS',
    CREATEACCOUNT_LOAD_ERROR: 'CREATEACCOUNT_LOAD_ERROR'
};

//accountNumber action type ends

//accountNumber action types

export const accountStatus = {
    ACCOUNTSTATUS_LOAD_START: 'ACCOUNTSTATUS_LOAD_START',
    ACCOUNTSTATUS_LOAD_SUCCESS: 'ACCOUNTSTATUS_LOAD_SUCCESS',
    ACCOUNTSTATUS_LOAD_ERROR: 'ACCOUNTSTATUS_LOAD_ERROR'
};

//accountNumber action type ends

//businessCategory action types

export const businessCategories = {
    BUSINESSCATEGORIES_LOAD_START: 'BUSINESSCATEGORIES_LOAD_START',
    BUSINESSCATEGORIES_LOAD_SUCCESS: 'BUSINESSCATEGORIES_LOAD_SUCCESS',
    BUSINESSCATEGORIES_LOAD_ERROR: 'BUSINESSCATEGORIES_LOAD_ERROR'
};

//businessCategory action type ends

//states action types

export const states = {
    STATES_LOAD_START: 'STATES_LOAD_START',
    STATES_LOAD_SUCCESS: 'STATES_LOAD_SUCCESS',
    STATES_LOAD_ERROR: 'STATES_LOAD_ERROR'
};

//states action type ends

//cardLogin action types

export const cardLogin = {
    CARDLOGIN_LOAD_START: 'CARDLOGIN_LOAD_START',
    CARDLOGIN_LOAD_SUCCESS: 'CARDLOGIN_LOAD_SUCCESS',
    CARDLOGIN_LOAD_ERROR: 'CARDLOGIN_LOAD_ERROR'
};

//cardLogin action type ends

//auth action types
export const login = {
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_START: 'REGISTER_START',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROE',
    SET_MESSAGE: 'SET_MESSAGE',
    CLEAR_MESSAGE: 'CLEAR_MESSAGE',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    LOGIN_START: 'LOGIN_START'
};
//end auth action types
//profile setup

export const setupProfile = {
    PROFILESETUP_LOAD_START: 'PROFILE_SETUPLOAD_START',
    PROFILESETUP_LOAD_SUCCESS: 'PROFILESETUP_LOAD_SUCCESS',
    PROFILESETUP_LOAD_ERROR: 'PROFILESETUP_LOAD_ERROR',
    BVN_NIN_LOAD_ERROR: 'BVN_NIN_LOAD_ERROR',
    BVN_NIN_LOAD_ERRORI: 'BVN_NIN_LOAD_ERRORI',
    BVN_NIN_LOAD_ERRORII: 'BVN_NIN_LOAD_ERRORII',
    BVN_NIN_LOAD_ERRORIII: 'BVN_NIN_LOAD_ERRORIII',
    BVN_NIN_LOAD_SUCCESS: 'BVN_NIN_LOAD_SUCCESS',
    BVN_NIN_LOAD_PENDING: 'BVN_NIN_LOAD_PENDING'
};
//profile setup end
//complete profile action type start

export const compProfile = {
    PROFILE_LOAD_START: 'PROFILE_LOAD_START',
    PROFILE_LOAD_SUCCESS: 'PROFILE_LOAD_SUCCESS',
    PROFILE_LOAD_ERROR: 'PROFILE_LOAD_ERROR'
};

//complete profile action type end

//ot action type start

export const otp = {
    OTP_LOAD_START: 'OTP_LOAD_START',
    OTP_LOAD_SUCCESS: 'OTP_LOAD_SUCCESS',
    OTP_LOAD_ERROR: 'OTP_LOAD_ERROR'
};
//otp action type end

//complete profile start
export const completeProfile = {
    COMP_PROFILE_LOAD_START: 'COMP_PROFILE_LOAD_START',
    COMP_PROFILE_LOAD_SUCCESS: 'COMP_PROFILE_LOAD_SUCCESS',
    COMP_PROFILE_LOAD_ERROR: 'COMP_PROFILE_LOAD_ERROR'
};
//complete profile end

//create new user account
export const newUserCreateAccount = {
    CREATE_NEW_ACCOUNT_LOAD_START: 'CREATE_NEW_ACCOUNT_LOAD_START',
    CREATE_NEW_ACCOUNT_LOAD_SUCCESS: 'CREATE_NEW_ACCOUNT_LOAD_SUCCESS',
    CREATE_NEW_ACCOUNT_LOAD_ERROR: 'CREATE_NEW_ACCOUNT_LOAD_ERROR'
};
//create new user end

//get new user account start

export const getNewUserAccount = {
    GET_NEW_ACCOUNT_LOAD_START: 'GET_NEW_ACCOUNT_LOAD_START',
    GET_NEW_ACCOUNT_LOAD_SUCCESS: 'GET_NEW_ACCOUNT_LOAD_SUCCESS',
    GET_NEW_ACCOUNT_LOAD_ERROR: 'GET_NEW_ACCOUNT_LOAD_ERROR'
};

//get new user account end

//create new user Corp account
export const newUserCreateCorpAccount = {
    CREATE_NEW_CORP_ACCOUNT_LOAD_START: 'CREATE_NEW_CORP_ACCOUNT_LOAD_START',
    CREATE_NEW_CORP_ACCOUNT_LOAD_SUCCESS:
        'CREATE_NEW_CORP_ACCOUNT_LOAD_SUCCESS',
    CREATE_NEW_CORP_ACCOUNT_LOAD_ERROR: 'CREATE_NEW_CORP_ACCOUNT_LOAD_ERROR'
};
//create new user Corp end

//ACCOUNT STATUS START

//ACCOUNT STATS END
