//country action types
export const country = {
    COUNTRY_LOAD_START: 'COUNTRY_LOAD_START',
    COUNTRY_LOAD_SUCCESS: 'COUNTRY_LOAD_SUCCESS',
    COUNTRY_LOAD_ERROR: 'COUNTRY_LOAD_ERROR'
};
//country action types end

//banks action types
export const banks = {
    BANK_LOAD_START: 'BANK_LOAD_START',
    BANK_LOAD_SUCCESS: 'BANK_LOAD_SUCCESS',
    BANK_LOAD_ERROR: 'BANK_LOAD_ERROR'
};
//banks action types end
//biller category action types
export const billerCategory = {
    BILLERCATEGORY_LOAD_START: 'BILLERCATEGORY_LOAD_START',
    BILLERCATEGORY_LOAD_SUCCESS: 'BILLERCATEGORY_LOAD_SUCCESS',
    BILLERCATEGORY_LOAD_ERROR: 'BILLERCATEGORY_LOAD_ERROR'
};
//biller category action types end

//banks action types
export const billerType = {
    BILLERTYPE_LOAD_START: 'BILLERTYPE_LOAD_START',
    BILLERTYPE_LOAD_SUCCESS: 'BILLERTYPE_LOAD_SUCCESS',
    BILLERTYPE_LOAD_ERROR: 'BILLERTYPE_LOAD_ERROR'
};
//banks action types end
//banks action types
export const billerPlan = {
    BILLERPLAN_LOAD_START: 'BILLERPLAN_LOAD_START',
    BILLERPLAN_LOAD_SUCCESS: 'BILLERPLAN_LOAD_SUCCESS',
    BILLERPLAN_LOAD_ERROR: 'BILLERPLAN_LOAD_ERROR'
};
//banks action types end

//language action types

export const languages = {
    LANGUAGE_LOAD_START: 'LANGUAGE_LOAD_START',
    LANGUAGE_LOAD_SUCCESS: 'LANGUAGE_LOAD_SUCCESS',
    LANGUAGE_LOAD_ERROR: 'LANGUAGE_LOAD_ERROR'
};

//language action type ends

//Airtime action types

export const airtime = {
    AIRTIME_LOAD_START: 'AIRTIME_LOAD_START',
    AIRTIME_LOAD_SUCCESS: 'AIRTIME_LOAD_SUCCESS',
    AIRTIME_LOAD_ERROR: 'AIRTIME_LOAD_ERROR'
};

//Airtime action type ends

//Bills action types

export const bills = {
    BILLS_LOAD_START: 'BILLS_LOAD_START',
    BILLS_LOAD_SUCCESS: 'BILLS_LOAD_SUCCESS',
    BILLS_LOAD_ERROR: 'BILLS_LOAD_ERROR'
};

//Bills action type ends

//Internal action types

export const internalBank = {
    INTERNALBANK_LOAD_START: 'INTERNALBANK_LOAD_START',
    INTERNALBANK_LOAD_SUCCESS: 'INTERNALBANK_LOAD_SUCCESS',
    INTERNALBANK_LOAD_ERROR: 'INTERNALBANK_LOAD_ERROR'
};

//Internal action type ends
//Inter action types

export const interBank = {
    INTERBANK_LOAD_START: 'INTERBANK_LOAD_START',
    INTERBANK_LOAD_SUCCESS: 'INTERBANK_LOAD_SUCCESS',
    INTERBANK_LOAD_ERROR: 'INTERBANK_LOAD_ERROR'
};

//Inter action type ends

//Inter action types

export const interBankEnquiry = {
    INTERBANKENQUIRY_LOAD_START: 'INTERBANKENQUIRY_LOAD_START',
    INTERBANKENQUIRY_LOAD_SUCCESS: 'INTERBANKENQUIRY_LOAD_SUCCESS',
    INTERBANKENQUIRY_LOAD_ERROR: 'INTERBANKENQUIRY_LOAD_ERROR'
};

//Inter action type ends

//balanceEnquiry action types

export const balanceEnquiry = {
    BALANCEENQUIRY_LOAD_START: 'BALANCEENQUIRY_LOAD_START',
    BALANCEENQUIRY_LOAD_SUCCESS: 'BALANCEENQUIRY_LOAD_SUCCESS',
    BALANCEENQUIRY_LOAD_ERROR: 'BALANCEENQUIRY_LOAD_ERROR'
};

//balanceENquiry action type ends

//transactionHistory action types

export const transactionHistory = {
    TRANSACTIONHISTORY_LOAD_START: 'TRANSACTIONHISTORY_LOAD_START',
    TRANSACTIONHISTORY_LOAD_SUCCESS: 'TRANSACTIONHISTORY_LOAD_SUCCESS',
    TRANSACTIONHISTORY_LOAD_ERROR: 'TRANSACTIONHISTORY_LOAD_ERROR'
};

//transactionHistory action type ends

//transactionElevate action types

export const transactionElevate = {
    TRANSACTIONELEVATE_LOAD_START: 'TRANSACTIONELEVATE_LOAD_START',
    TRANSACTIONELEVATE_LOAD_SUCCESS: 'TRANSACTIONELEVATE_LOAD_SUCCESS',
    TRANSACTIONELEVATE_LOAD_ERROR: 'TRANSACTIONELEVATE_LOAD_ERROR'
};

//transactionElevate action type ends

//getBeneficiaries action types

export const getBeneficiaries = {
    GETBENEFICIARIES_LOAD_START: 'GETBENEFICIARIES_LOAD_START',
    GETBENEFICIARIES_LOAD_SUCCESS: 'GETBENEFICIARIES_LOAD_SUCCESS',
    GETBENEFICIARIES_LOAD_ERROR: 'GETBENEFICIARIES_LOAD_ERROR'
};

//getBeneficiaries action type ends

//postBeneficiaries action types

export const postBeneficiaries = {
    POSTBENEFICIARIES_LOAD_START: 'POSTBENEFICIARIES_LOAD_START',
    POSTBENEFICIARIES_LOAD_SUCCESS: 'POSTBENEFICIARIES_LOAD_SUCCESS',
    POSTBENEFICIARIES_LOAD_ERROR: 'POSTBENEFICIARIES_LOAD_ERROR'
};

//postBeneficiaries action type ends

//transactionHistory action types

export const bulkTransfer = {
    BULKTRANSFER_LOAD_START: 'BULKTRANSFER_LOAD_START',
    BULKTRANSFER_LOAD_SUCCESS: 'BULKTRANSFER_LOAD_SUCCESS',
    BULKTRANSFER_LOAD_ERROR: 'BULKTRANSFER_LOAD_ERROR'
};

//transactionHistory action type ends

//verifyBank action types

export const verifyBank = {
    VERIFYBANK_LOAD_START: 'VERIFYBANK_LOAD_START',
    VERIFYBANK_LOAD_SUCCESS: 'VERIFYBANK_LOAD_SUCCESS',
    VERIFYBANK_LOAD_ERROR: 'VERIFYBANK_LOAD_ERROR'
};

//verifyBank action type ends

//VerifyCurrency action types

export const verifyCurrency = {
    VERIFYCURRENCY_LOAD_START: 'VERIFYCURRENCY_LOAD_START',
    VERIFYCURRENCY_LOAD_SUCCESS: 'VERIFYCURRENCY_LOAD_SUCCESS',
    VERIFYCURRENCY_LOAD_ERROR: 'VERIFYCURRENCY_LOAD_ERROR'
};

//VerifyCurrency action type ends

//transactionHistory action types

export const internationalTransfer = {
    INTERNATIONALTRANSFER_LOAD_START: 'INTERNATIONALTRANSFER_LOAD_START',
    INTERNATIONALTRANSFER_LOAD_SUCCESS: 'INTERNATIONALTRANSFER_LOAD_SUCCESS',
    INTERNATIONALTRANSFER_LOAD_ERROR: 'INTERNATIONALTRANSFER_LOAD_ERROR'
};

//transactionHistory action type ends

//auth action types
export const login = {
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROE',
    SET_MESSAGE: 'SET_MESSAGE',
    CLEAR_MESSAGE: 'CLEAR_MESSAGE',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT'
};
//end auth action types
