import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import HomeMain from './home';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Elevate</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HomeMain />
        </div>
    );
}
